# Generated by Django 3.2.12 on 2022-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='publication_date',
            new_name='date',
        ),
    ]
